//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.XtraCompositeModule.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.XtraCompositeModule.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap add_48x48 {
            get {
                object obj = ResourceManager.GetObject("add_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap add_to_favorites_48x48 {
            get {
                object obj = ResourceManager.GetObject("add_to_favorites_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap alarm_48x48 {
            get {
                object obj = ResourceManager.GetObject("alarm_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap alert_24x24 {
            get {
                object obj = ResourceManager.GetObject("alert_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap alert_32x32 {
            get {
                object obj = ResourceManager.GetObject("alert_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap alert_48x48 {
            get {
                object obj = ResourceManager.GetObject("alert_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap app_48x48 {
            get {
                object obj = ResourceManager.GetObject("app_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Icon applications {
            get {
                object obj = ResourceManager.GetObject("applications", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Bitmap attached_48x48 {
            get {
                object obj = ResourceManager.GetObject("attached_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap back_48x48 {
            get {
                object obj = ResourceManager.GetObject("back_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap block_24x24 {
            get {
                object obj = ResourceManager.GetObject("block_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap block_32x32 {
            get {
                object obj = ResourceManager.GetObject("block_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap block_48x48 {
            get {
                object obj = ResourceManager.GetObject("block_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap blue_flag_48x48 {
            get {
                object obj = ResourceManager.GetObject("blue_flag_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bold_48x48 {
            get {
                object obj = ResourceManager.GetObject("bold_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap burning_48x48 {
            get {
                object obj = ResourceManager.GetObject("burning_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap button_48x48 {
            get {
                object obj = ResourceManager.GetObject("button_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap button_blue_48x48 {
            get {
                object obj = ResourceManager.GetObject("button_blue_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap button_eject_48x48 {
            get {
                object obj = ResourceManager.GetObject("button_eject_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap button_eject2_48x48 {
            get {
                object obj = ResourceManager.GetObject("button_eject2_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap button_fast_forward_48x48 {
            get {
                object obj = ResourceManager.GetObject("button_fast_forward_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap button_fast_forward2_48x48 {
            get {
                object obj = ResourceManager.GetObject("button_fast_forward2_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap button_next_48x48 {
            get {
                object obj = ResourceManager.GetObject("button_next_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap button_next2_48x48 {
            get {
                object obj = ResourceManager.GetObject("button_next2_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap button_pause_48x48 {
            get {
                object obj = ResourceManager.GetObject("button_pause_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap button_pause2_48x48 {
            get {
                object obj = ResourceManager.GetObject("button_pause2_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap button_play_48x48 {
            get {
                object obj = ResourceManager.GetObject("button_play_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap button_play2_48x48 {
            get {
                object obj = ResourceManager.GetObject("button_play2_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap button_previous_48x48 {
            get {
                object obj = ResourceManager.GetObject("button_previous_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap button_previous2_48x48 {
            get {
                object obj = ResourceManager.GetObject("button_previous2_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap button_red_48x48 {
            get {
                object obj = ResourceManager.GetObject("button_red_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap button_rewind_48x48 {
            get {
                object obj = ResourceManager.GetObject("button_rewind_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap button_rewind2_48x48 {
            get {
                object obj = ResourceManager.GetObject("button_rewind2_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap button_stop_48x48 {
            get {
                object obj = ResourceManager.GetObject("button_stop_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap button_stop2_48x48 {
            get {
                object obj = ResourceManager.GetObject("button_stop2_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap calculator_48x48 {
            get {
                object obj = ResourceManager.GetObject("calculator_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap cascade_48x48 {
            get {
                object obj = ResourceManager.GetObject("cascade_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap cd_48x48 {
            get {
                object obj = ResourceManager.GetObject("cd_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap cd_burn_48x48 {
            get {
                object obj = ResourceManager.GetObject("cd_burn_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap computer_48x48 {
            get {
                object obj = ResourceManager.GetObject("computer_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap computer_off_48x48 {
            get {
                object obj = ResourceManager.GetObject("computer_off_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap computer_ok_48x48 {
            get {
                object obj = ResourceManager.GetObject("computer_ok_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap computer_on_48x48 {
            get {
                object obj = ResourceManager.GetObject("computer_on_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap config_48x48 {
            get {
                object obj = ResourceManager.GetObject("config_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap contacts_48x48 {
            get {
                object obj = ResourceManager.GetObject("contacts_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap copy_48x48 {
            get {
                object obj = ResourceManager.GetObject("copy_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap cut_48x48 {
            get {
                object obj = ResourceManager.GetObject("cut_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap delete_24x24 {
            get {
                object obj = ResourceManager.GetObject("delete_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap delete_32x32 {
            get {
                object obj = ResourceManager.GetObject("delete_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap delete_48x48 {
            get {
                object obj = ResourceManager.GetObject("delete_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap dialog_48x48 {
            get {
                object obj = ResourceManager.GetObject("dialog_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap down_48x48 {
            get {
                object obj = ResourceManager.GetObject("down_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap edit_document_48x48 {
            get {
                object obj = ResourceManager.GetObject("edit_document_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap email_48x48 {
            get {
                object obj = ResourceManager.GetObject("email_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap export_48x48 {
            get {
                object obj = ResourceManager.GetObject("export_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap favorites_48x48 {
            get {
                object obj = ResourceManager.GetObject("favorites_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap file_48x48 {
            get {
                object obj = ResourceManager.GetObject("file_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap filter_48x48 {
            get {
                object obj = ResourceManager.GetObject("filter_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap folder_close_48x48 {
            get {
                object obj = ResourceManager.GetObject("folder_close_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap folder_open_48x48 {
            get {
                object obj = ResourceManager.GetObject("folder_open_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap go_48x48 {
            get {
                object obj = ResourceManager.GetObject("go_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap green_flag_48x48 {
            get {
                object obj = ResourceManager.GetObject("green_flag_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap hd_48x48 {
            get {
                object obj = ResourceManager.GetObject("hd_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap home_48x48 {
            get {
                object obj = ResourceManager.GetObject("home_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap horizontal_48x48 {
            get {
                object obj = ResourceManager.GetObject("horizontal_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap import_48x48 {
            get {
                object obj = ResourceManager.GetObject("import_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap info_24x24 {
            get {
                object obj = ResourceManager.GetObject("info_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap info_32x32 {
            get {
                object obj = ResourceManager.GetObject("info_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap info_48x48 {
            get {
                object obj = ResourceManager.GetObject("info_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap internet_48x48 {
            get {
                object obj = ResourceManager.GetObject("internet_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap italic_48x48 {
            get {
                object obj = ResourceManager.GetObject("italic_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap key_48x48 {
            get {
                object obj = ResourceManager.GetObject("key_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap large_icons_48x48 {
            get {
                object obj = ResourceManager.GetObject("large_icons_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap next_48x48 {
            get {
                object obj = ResourceManager.GetObject("next_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap notes_48x48 {
            get {
                object obj = ResourceManager.GetObject("notes_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ok_24x24 {
            get {
                object obj = ResourceManager.GetObject("ok_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ok_32x32 {
            get {
                object obj = ResourceManager.GetObject("ok_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ok_48x48 {
            get {
                object obj = ResourceManager.GetObject("ok_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap open_document_48x48 {
            get {
                object obj = ResourceManager.GetObject("open_document_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap open_folder_48x48 {
            get {
                object obj = ResourceManager.GetObject("open_folder_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap padlock_close_48x48 {
            get {
                object obj = ResourceManager.GetObject("padlock_close_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap padlock_open_48x48 {
            get {
                object obj = ResourceManager.GetObject("padlock_open_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap paste_48x48 {
            get {
                object obj = ResourceManager.GetObject("paste_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap print_48x48 {
            get {
                object obj = ResourceManager.GetObject("print_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap quote_48x48 {
            get {
                object obj = ResourceManager.GetObject("quote_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap red_flag_48x48 {
            get {
                object obj = ResourceManager.GetObject("red_flag_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap redo_48x48 {
            get {
                object obj = ResourceManager.GetObject("redo_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap refresh_48x48 {
            get {
                object obj = ResourceManager.GetObject("refresh_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap remove_24x24 {
            get {
                object obj = ResourceManager.GetObject("remove_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap remove_32x32 {
            get {
                object obj = ResourceManager.GetObject("remove_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap remove_48x48 {
            get {
                object obj = ResourceManager.GetObject("remove_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap running_48x48 {
            get {
                object obj = ResourceManager.GetObject("running_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap save_48x48 {
            get {
                object obj = ResourceManager.GetObject("save_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap save_as_48x48 {
            get {
                object obj = ResourceManager.GetObject("save_as_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap script_48x48 {
            get {
                object obj = ResourceManager.GetObject("script_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap script_add_48x48 {
            get {
                object obj = ResourceManager.GetObject("script_add_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap script_delete_48x48 {
            get {
                object obj = ResourceManager.GetObject("script_delete_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap search_48x48 {
            get {
                object obj = ResourceManager.GetObject("search_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap show_info_24x24 {
            get {
                object obj = ResourceManager.GetObject("show_info_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap show_info_32x32 {
            get {
                object obj = ResourceManager.GetObject("show_info_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap show_info_48x48 {
            get {
                object obj = ResourceManager.GetObject("show_info_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap small_icons_48x48 {
            get {
                object obj = ResourceManager.GetObject("small_icons_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap software_48x48 {
            get {
                object obj = ResourceManager.GetObject("software_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap stop_24x24 {
            get {
                object obj = ResourceManager.GetObject("stop_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap stop_32x32 {
            get {
                object obj = ResourceManager.GetObject("stop_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap stop_48x48 {
            get {
                object obj = ResourceManager.GetObject("stop_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap tasks_48x48 {
            get {
                object obj = ResourceManager.GetObject("tasks_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap text_48x48 {
            get {
                object obj = ResourceManager.GetObject("text_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap themes_48x48 {
            get {
                object obj = ResourceManager.GetObject("themes_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap trash_48x48 {
            get {
                object obj = ResourceManager.GetObject("trash_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap trash_full_48x48 {
            get {
                object obj = ResourceManager.GetObject("trash_full_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap undo_48x48 {
            get {
                object obj = ResourceManager.GetObject("undo_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap up_48x48 {
            get {
                object obj = ResourceManager.GetObject("up_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap update_48x48 {
            get {
                object obj = ResourceManager.GetObject("update_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap user_48x48 {
            get {
                object obj = ResourceManager.GetObject("user_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap users_48x48 {
            get {
                object obj = ResourceManager.GetObject("users_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap vertical_48x48 {
            get {
                object obj = ResourceManager.GetObject("vertical_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap view__48x48 {
            get {
                object obj = ResourceManager.GetObject("view__48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap view__48x481 {
            get {
                object obj = ResourceManager.GetObject("view__48x481", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap window_48x48 {
            get {
                object obj = ResourceManager.GetObject("window_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap wizard_48x48 {
            get {
                object obj = ResourceManager.GetObject("wizard_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap yellow_flag_48x48 {
            get {
                object obj = ResourceManager.GetObject("yellow_flag_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
