//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChipAndDale.Main.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChipAndDale.Main.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Add {
            get {
                object obj = ResourceManager.GetObject("Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Cancel_18 {
            get {
                object obj = ResourceManager.GetObject("Cancel_18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Форум.
        /// </summary>
        internal static string ForumInfoSourceType {
            get {
                return ResourceManager.GetString("ForumInfoSourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Джабер.
        /// </summary>
        internal static string JabberSourceType {
            get {
                return ResourceManager.GetString("JabberSourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лист.
        /// </summary>
        internal static string LetterInfoSourceType {
            get {
                return ResourceManager.GetString("LetterInfoSourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пошта.
        /// </summary>
        internal static string MailInfoSourceType {
            get {
                return ResourceManager.GetString("MailInfoSourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не встановлено пыдключення до бази даних.
        /// </summary>
        internal static string NoDbConnectionMessage {
            get {
                return ResourceManager.GetString("NoDbConnectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка під час роботи з довідником (редагування).
        /// </summary>
        internal static string NsiEditFormErrorMessage {
            get {
                return ResourceManager.GetString("NsiEditFormErrorMessage", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap NsiGeneral {
            get {
                object obj = ResourceManager.GetObject("NsiGeneral", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка під час завантаження довідників.
        /// </summary>
        internal static string NsiLoadErrorMessage {
            get {
                return ResourceManager.GetString("NsiLoadErrorMessage", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap NsiUser {
            get {
                object obj = ResourceManager.GetObject("NsiUser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка під час роботи з довідником (перегляд).
        /// </summary>
        internal static string NsiViewFormErrorMessage {
            get {
                return ResourceManager.GetString("NsiViewFormErrorMessage", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Ok_18 {
            get {
                object obj = ResourceManager.GetObject("Ok_18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        internal static string PhoneInfoSourceType {
            get {
                return ResourceManager.GetString("PhoneInfoSourceType", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Recycle_18 {
            get {
                object obj = ResourceManager.GetObject("Recycle_18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Refresh_18 {
            get {
                object obj = ResourceManager.GetObject("Refresh_18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Remove {
            get {
                object obj = ResourceManager.GetObject("Remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
