//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChipAndDale.Request.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChipAndDale.Request.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap AddRequest_18 {
            get {
                object obj = ResourceManager.GetObject("AddRequest_18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аналізується.
        /// </summary>
        internal static string AnalyzeRequestState {
            get {
                return ResourceManager.GetString("AnalyzeRequestState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Швидкий перегляд вимкнений.
        /// </summary>
        internal static string AttachQuickViewTurnOff {
            get {
                return ResourceManager.GetString("AttachQuickViewTurnOff", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Cancel {
            get {
                object obj = ResourceManager.GetObject("Cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Cancel_18 {
            get {
                object obj = ResourceManager.GetObject("Cancel_18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрите.
        /// </summary>
        internal static string CloseRequestState {
            get {
                return ResourceManager.GetString("CloseRequestState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви бажаєте видалити фільтр.
        /// </summary>
        internal static string DeleteFilterMessage {
            get {
                return ResourceManager.GetString("DeleteFilterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виконано.
        /// </summary>
        internal static string DoneRequestState {
            get {
                return ResourceManager.GetString("DoneRequestState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В роботі.
        /// </summary>
        internal static string InWorkRequestState {
            get {
                return ResourceManager.GetString("InWorkRequestState", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Ok {
            get {
                object obj = ResourceManager.GetObject("Ok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ok_18 {
            get {
                object obj = ResourceManager.GetObject("Ok_18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відкрите.
        /// </summary>
        internal static string OpenRequestState {
            get {
                return ResourceManager.GetString("OpenRequestState", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Recycle {
            get {
                object obj = ResourceManager.GetObject("Recycle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Recycle_18 {
            get {
                object obj = ResourceManager.GetObject("Recycle_18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Refresh {
            get {
                object obj = ResourceManager.GetObject("Refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Refresh_18 {
            get {
                object obj = ResourceManager.GetObject("Refresh_18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Request {
            get {
                object obj = ResourceManager.GetObject("Request", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Звернення було змінено.
        /// </summary>
        internal static string RequestAlreadyChanged {
            get {
                return ResourceManager.GetString("RequestAlreadyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Звернення було видалено.
        /// </summary>
        internal static string RequestAlreadyRemoved {
            get {
                return ResourceManager.GetString("RequestAlreadyRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При обробці звернення виникла помилка.
        /// </summary>
        internal static string RequestApplyError {
            get {
                return ResourceManager.GetString("RequestApplyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нове зверненя створено.
        /// </summary>
        internal static string RequestCreateSuccess {
            get {
                return ResourceManager.GetString("RequestCreateSuccess", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap RequestList {
            get {
                object obj = ResourceManager.GetObject("RequestList", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Звернення не знайдене.
        /// </summary>
        internal static string RequestNotFound {
            get {
                return ResourceManager.GetString("RequestNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Звернення не є корректним.
        /// </summary>
        internal static string RequestNotValid {
            get {
                return ResourceManager.GetString("RequestNotValid", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap RequestPeriodReport_18 {
            get {
                object obj = ResourceManager.GetObject("RequestPeriodReport_18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Звернення оновлено.
        /// </summary>
        internal static string RequestRefreshed {
            get {
                return ResourceManager.GetString("RequestRefreshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Звернення збережене.
        /// </summary>
        internal static string RequestSaveSuccess {
            get {
                return ResourceManager.GetString("RequestSaveSuccess", resourceCulture);
            }
        }
    }
}
